name: build-test-deply
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: run linter
        run: npm lint
      - name: run test
        run: npm test
      - name: deploy
        run: echo "Deployed Project"
